version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - "./appdata/grafana:/var/lib/grafana/"

  server:
    image: openjdk:17-oracle
    ports:
      - "8080:8080"
    working_dir: "/app"
    volumes:
      - "./appdata/server:/app"
    entrypoint: "java -jar -Dspring.profiles.active='test' server.jar"
