{
 "title": "RoomPicker",
 "tags": [ "roompicker" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "RoomPicker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total users in nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "roompicker_node_users_total", "legendFormat": "{{nodeId}}" }
   ]
  },
  {
   "title": "Total users diagram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 1 },
   "targets": [
    { "expr": "roompicker_total_users", "legendFormat": "Total users" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "roompicker_total_users", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "roompicker_total_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Picks per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(delta(roompicker_picks_1s_total[1m]))",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Inaccessible rooms (full or locked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "roompicker_locked_rooms", "legendFormat": "{{nodeId}}" }
   ]
  },
  {
   "title": "Number of rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "roompicker_rooms", "legendFormat": "{{nodeId}}" }
   ]
  }
 ]
}