management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
    default-models-expand-depth: -1

spring:
  graphql:
    graphiql:
      enabled: true
